
[window]
decorations = "Full"
# padding     = { x = 5, y = 5 }

[scrolling]
history     = 100000

[font]
normal      = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold        = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic      = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

size        = 12

[general]
import = [
  "~/.config/alacritty/themes/tokyo-night-storm.toml"
]
